### ISSUE TITLE
Bomb后端云管理工具

### ISSUE THREAD

**Issue by bowlders** [100steps/Blogs#29]
bomb后端云是什么？
是一个baas平台。
baas平台是什么？
baas（后端即服务：Backend as a Service），公司为移动应用开发者提供整合云后端的边界服务。
注意：是bomb，不是bmob！
然后附一个娱乐大众的文章。

好，说正经的。。。
http://www.bmob.cn/docs
就这一个网址，里面讲解十分详细。
各个方向的都可以看一下。
主要给移动端的看看，可以多给黄登一些时间和妹子相处，少写点api。

**Comment by SunDoge** [comment]
事实是，移动端对API的品味会变高，然后要求后台给出这个样子的API。。。

**Comment by Zhangjd** [comment]
既然有机会和大家分享, 可不可以用心一点, 而不是抛个官网出来然后对大家说 RTFM 呢?

以这个主题为例, 提问:

1. 除了 baas 还有什么 *aas ? 你们常用的新浪云, 阿里云, 腾讯云属于什么服务?
2. 除了提及的这家公司, 国内外还有什么同类的服务供应商? 哪家的产品更受欢迎? 文档更友好? 功能更丰富?
3. 这种服务的数据存储功能和传统的关系型数据库相比, 有什么特点? 适合用在哪些应用场景? 不妨举几个例子.
4. 既然你介绍了这个平台, 有没有写一个 demo 出来给大家看看?
