### ISSUE TITLE
被抽中来分享？先来 review 抽奖代码吧!

### ISSUE THREAD

**Issue by Zhangjd** [100steps/Blogs#5]
在群里看到的一份抽签代码:

```python
#!/bin/env python3
import sys,os,random
f = open("list.txt","r+")
flist = f.readlines()
random.shuffle(flist)
saturday = flist.pop()
sunday = flist.pop()
print(saturday.strip())
print(sunday.strip())
f = open("list.txt","w+")
f.writelines(flist)
```

不妨思考一下，得出以下疑点:

1. 文件被 open 了两次，没有调用 close 方法
2. random 模块生成的是伪随机数

然后问题来了，大家可以思考下答案:

* r+ 和 w+ 模式有何不同? 是否需要调用两次?
* 为什么说调用 close 方法是一个好习惯?
* 什么是伪随机数?
* 什么是随机数种子? 如果随机数种子相同，会有什么后果？
* 如何产生真随机数?
* 如果要自己实现 shuffle 算法，你们有什么思路?

**Comment by iThreeKing** [comment]
* r+打开文件会保持原文件内容不变，可以对文件进行读写;w+打开文件会将原文件内容删除，可以对文件进行读写
* 手动释放资源。如果不close()，那就要等到垃圾回收时自动释放资源。垃圾回收的时机不能确定也无法人为干预。
* 真正的随机数应该是某次实验过程中显示出来的随机分布概率，肯定是不可预测的，但是伪随机数是按照一定算法模拟出来的，这种模拟的结果就确定的。
后面问题留给你们

**Comment by SunDoge** [comment]
随机数好像可以用这个
[https://www.random.org/](url)

**Comment by snow-t** [comment]
因为电脑不可能做到真正的随机，所以随机数的生成主要依靠各种不可预知的因数，比如系统启动后的微秒数什么的，这些就叫随机数种子，当然也存在确定的随机数种子，如果使用这些确定的随机数种子那么就会产生相同的随机序列。（看了15分钟的总结，有错误请指正谢谢...）

**Comment by zhoulukuan** [comment]
说下我的理解吧：
- 关于真伪随机问题，个人觉得最重要的区别还是在于可否复现序列。因为伪随机在给定了随机数种子后，是根据一定的算法来生成随机数序列的，只要算法和种子是一定的，那么随机数序列本身是不会改变的
- 真随机数是要依靠物理条件而不是像伪随机那样一个个根据算法生成。通俗点说，类似于抛硬币，两次抛投前后没有任何联系，要实现真随机数就必须引入一些不确定的物理条件，在计算机上有很多，比如鼠标位置的改变和点击，流量的波动和变化，计算机内部的中断和噪声干扰等等……
- 据说linux内核内部是有专门的熵池来收集计算机内部的物理条件以供生成随机数的，希望有大神能解释一下工作过程吧。感觉如果熵池为空或者数据过多都挺麻烦的。
- 因为提到概率问题所以扯点题外话，就是在很多情况下，实际测量数据和理论数据的误差都是服从高斯分布（正态分布）的，这也是最小二乘法的由来。因为从理论上讲，最小二乘法的条件实际上就是我们实际测量值为出现概率最大的条件。

**Comment by hongruiqi** [comment]
**关于open**

文件操作的函数有两类

- open, read, write, close等系统函数，它们是对系统调用的直接封装。
- fopen, fread, fwrite, fclose等库函数，它们是对上一类函数的进一步封装，提供缓冲读写等高级功能。

而Python的底层是C语言实现的，Python的open函数则对应于C语言的fopen库函数。为避免混淆，后文中的open指的是系统调用的open函数，而非Python的open函数。

既然fopen是对open的封装，实现中一定是调用了open 的。先来看一下[open](http://man7.org/linux/man-pages/man2/open.2.html)的函数原型

`int open(const char *pathname, int flags);`

pathname是文件路径，flags是打开方式。

文档中可以看到所有flag的功能，摘录部分如下：

The argument flags must include one of the following access modes:
       O_RDONLY, O_WRONLY, or O_RDWR.  These request opening the file read-
       only, write-only, or read/write, respectively.

O_APPEND
              The file is opened in append mode.  Before each write(2), the
              file offset is positioned at the end of the file, as if with
              lseek(2).  

O_CREAT
              If the file does not exist, it will be created.  

O_TRUNC
              If the file already exists and is a regular file and the
              access mode allows writing (i.e., is O_RDWR or O_WRONLY) it
              will be truncated to length 0.

再来看一下[fopen](http://man7.org/linux/man-pages/man3/fopen.3.html)的。

`FILE *fopen(const char *path, const char *mode);`

其中mode有r，r+，w，w+，a，a+。

既然fopen调用了open，那么在实现中就一定会把r，r+，w，w+等mode转换成O_XXX的flag形式。那么转换的实现如下(https://android.googlesource.com/platform/bionic/+/ics-mr0/libc/stdio/flags.c)：

```
int
__sflags(const char *mode, int *optr)
{
	int ret, m, o;
	switch (*mode++) {
	case 'r':	/* open for reading */
		ret = __SRD;
		m = O_RDONLY;
		o = 0;
		break;
	case 'w':	/* open for writing */
		ret = __SWR;
		m = O_WRONLY;
		o = O_CREAT | O_TRUNC;
		break;
	case 'a':	/* open for appending */
		ret = __SWR;
		m = O_WRONLY;
		o = O_CREAT | O_APPEND;
		break;
	default:	/* illegal mode */
		errno = EINVAL;
		return (0);
	}
	/* [rwa]\+ or [rwa]b\+ means read and write */
	if (*mode == '+' || (*mode == 'b' && mode[1] == '+')) {
		ret = __SRW;
		m = O_RDWR;
	}
	*optr = m | o;
	return (ret);
}
```

主要看*optr的设置。

看代码可以知道他们之间的对应关系。

r对应O_RDONLY
r+对应O_RDWR
w对应O_WRONLY | O_CREAT | O_TRUNC
w+对应O_RDWR | O_CREAT | O_TRUNC
a对应O_WRONLY | O_CREAT | O_APPEND
a+对应O_RDWR | O_CREAT | O_APPEND

因此可以看出，w+比r+多了O_CREAT | O_TRUNC两个flag。那么回顾这两个flag的作用，可知w+在文件不存在时会自动创建文件，文件存在时会先清空原文件的内容。r+和w+都从文件开头开始写数据，区别在于，w+在写入前已清空了文件，不存在旧的数据；而r+则是逐渐覆盖写入，文件中会同时存在新数据和旧数据（还未被覆盖的）。

**Comment by hongruiqi** [comment]
**关于close**

首先，打开的资源使用完必须保证尽快关闭，这是一定要做到的，不能依赖垃圾回收。特别是服务端长期运行的程序，资源关闭拖得越久，则残留下的越多。而每个进程能够打开的文件数是有限的，超出之后，进程就开始奔溃了。

而对于这段Python程序就比较有趣了。

第一次和第二次打开的文件赋值给了同一个变量f。
而Python的垃圾回收和Java的不同，前者是基于引用计数的。大家应该想到了，在第二次打开文件赋值给f的时候，第一次打开的文件失去了最后一个引用，被自动关闭了，这里并不会引起资源泄露。

另外提到一点，资源尽量不要在逻辑流程中手工调用close关闭，而是应该尽可能的使用各个语言的特性，让资源离开作用域时被自动关闭。

这里的特性，在Python里是
```
    with open("abc.txt") as f:
          // do something with f
```
在C++里可以通过RAII（自行谷歌）
在Go里可以通过defer
在坑爹的Java里不得不通过丑陋的try catch finally

原因如下

首先，手工的资源管理容易遗漏，特别是在后期维护的时候。

例如：

```
f = open("abc.txt")
// long procedure
f.close()
```

假设有天某人在long procedure里加了个判断，不满足某些条件时直接return。因为代码太长，可能不会注意到几百行之后的f.close()，忘了还有资源要关闭，于是资源泄露了。

如果说上面这种情况还可以通过细心避免的话，那么再来看看发生异常的情况？

```
f = open("abc.txt")
foo()
f.close()
```

即使能够保证foo的逻辑本身不抛出异常，你也不能保证foo调用的其它函数不抛出异常。即使现在不会抛出，也不能保证以后不会有人改。一旦抛出异常，f.close()就不会执行，资源就泄露了。

在C++这种需要手工管理内存的语言里，这类机制可以有效减少内存泄露。
在具有垃圾回收的语言里，这类机制可以保证资源及时释放。

最后再次黑一下Java及其丑陋的try catch finally，谁用谁知道。

**Comment by tugui** [comment]
接着琦哥的发言，其实close等函数的使用，说到底是**资源管理**的问题，这里的资源包括了各种流(file-object)和连接(数据库)等等。而在操作的过程中，可能会出现异常或中断等情况，导致相关句柄(handle)没有正确关闭，就会一直占用内存空间。所以许多语言将这些东西进行了整合，形成了关于**异常处理**的语法糖或者叫语言特性。其中Python是封装得比较彻底的，而PHP、Java这些的语法就接近于C定义的原始try...catch结构，值得一提的是C++中RAII将资源转化为对象的思想。嗯，其实我觉得好的特性是能够简化代码、减轻工作量的，但是我们更应该关注核心的内容，也就是在这些封装的背后想优化或是隐藏的东西——不要因为人家帮你做了，你就可以不去了解整个过程。

另外要提的一点就是，在PHP的PDO中并没有出现类似close的函数供使用，然后这是我从官方文档找到的一段话：

> Upon successful connection to the database, an instance of the PDO class is returned to your script. The connection remains active for the lifetime of that PDO object. To close the connection, you need to destroy the object by ensuring that all remaining references to it are deleted--you do this by assigning NULL to the variable that holds the object. If you don't do this explicitly, PHP will automatically close the connection when your script ends.

也就是说，PDO将数据库连接以**类似指针**的方式进行操作，当不需要时只要将其设置为NULL就可以了，这也算是面向对象思想的一种体现吧。正如琦哥所说，在某些并发量大的情况下，主动释放资源可能对程序性能的提升会有帮助(甚至是解决瓶颈)，因为MySQL等数据库软件的并发连接数也是有限制的，及时地关闭连接可以保证数据库的处理效率...或者用持久化连接等办法来进行处理。
